site_name: Percy Jackson RPG - Regras 2.0
site_url: https://gabrielgomeso.github.io/pjrpg-rules/
theme:
  name: material
plugins:
    - awesome-pages:
        collapse_single_pages: true
    - search

 